apiVersion: v1
kind: Service
metadata:
  name: churn-inference-service
spec:
  selector:
    app: churn-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
